### PR TITLE
fix #10 bower update to px-datetime-common@3.2.2

### LINKED ISSUE #10: px-datetime-field field miscalculates width in IE/Edge
## Issue
It appears that as inputs are changed or as the user types into the px-datetime-field, the calculated inline width is incorrect when using browsers other than Chrome. Due to this miscalculation, the strings entered are not fully legible and are either cut off to the left or the right of the individual input field.

## Affected
This effects both Win/IE and Win/Firefox.

#### Mac Chrome (normal)
px-datetime-mac-chrome
px-datetime-mac-chrome-time

#### Win/Edge (not working as expected)
px-datetime-win-edge
px-datetime-win-edge-time

#### Win/Firefox has similar problems, but not at the same time.
px-datetime-win-firefox-default
px-datetime-win-firefox-mmddyyyy
px-datetime-win-firefox-time

### PR DESCRIPTION
**Pull request by joshsylvester**
- bower update to new minimum version of px-datetime-common
- fixes #10

@sheela-svmx
@mallik-svmx

### CODE REVIEW

**Comment by evanjd** [comment]
Is this needed? `^3.0.0` matches `3.x.x` (including `3.2.2`) - anyone who clones and runs `bower install` on this repo will get it.

(likewise, `bower update` if you've already checked it out will upgrade the dependency)

**Comment by joshsylvester** [comment]
@evanjd that is what i assumed should work as well - but if another application is using `px-datetime-field` at the last version, even with running `bower update`, it's not rebuilding `px-datetime-field` to pull in the new code - it appears to pull in the dependency, but not use the new code (from `px-datetime-common@3.2.2`) at all, leaving the field still broken.

I'm happy to ignore this PR if it was working properly through the dependency tree - but it doesn't appear to.  I'm open for suggestions if you have any.

**Comment by evanjd** [comment]
@joshsylvester My bad, I didn't think about how the dependencies were linked.

**Review by arongraham-ge — APPROVED** [review]

**Review by mallik-svmx — APPROVED** [review]

**Comment by joshsylvester** [comment]
build again

**Comment by joshsylvester** [comment]
@arongraham-ge @evanjd the travis build is failing, but i don't know too much about it - should we merge anyways?

**Comment by evanjd** [comment]
@joshsylvester Delete and re-generate `yarn.lock` and `package-lock.json`, should work after that.

https://github.com/predix-ui/maintainer-cheat-sheet/wiki/How-to:-regenerate-lock-files

**Comment by joshsylvester** [comment]
@evanjd @arongraham-ge what should we do on this build / PR? it's getting delayed because of the travis build, which is not currently passing on this branch - and all of the same tests fail on master. since this patch is not changing any code of the component, can it be merged?

**Pull request merged**
